require 'open-uri'
require 'nokogiri'
require 'pry'

require_relative './boston_events/version'
require_relative './boston_events/cli'
require_relative './boston_events/event'
require_relative './boston_events/category'
require_relative './boston_events/sponsor'
require_relative './boston_events/venue'
require_relative './boston_events/scraper'
